# -*- coding: utf-8 -*-
"""practical 4/10/23

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xyom-gEH4gnyfHNdfwl_5gjvwWCrW7sS
"""

import pandas as pd
data={
    "Product Name":['Computer','Kurtti','AC','Feriz'],
    "Category":['Electronics','Clothing','Home','Kitchen'],
    "Price":[50000,2000,5000,6000],
    "Quantity Slod":[2,10,2,1]
}
df=pd.DataFrame(data)
df

data_avrg = df.pivot_table(values='Price', index='Category', aggfunc='mean')
data_avrg

pivot_table= df.pivot_table(values=['Price', 'Quantity Slod'], index='Category', aggfunc={'Price': 'mean', 'Quantity Slod': 'sum'})
pivot_table.columns = ['Mean Price', 'Total Quantity Slod']
pivot_table['Total Revenue'] = pivot_table['Mean Price'] * pivot_table['Total Quantity Slod']
pivot_table

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('/content/mtcars (1).csv')
data

plt.figure(figsize=(8, 6))
plt.hist(data['mpg'], bins=10, edgecolor='k', color='pink')
plt.title('Histogram of MPG (Miles per gallon)')
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(data['wt'], data['mpg'], color='yellow', marker='s')
plt.title('Scatter Plot: Car Weight vs. MPG')
plt.xlabel('Car Weight')
plt.ylabel('MPG')
plt.show()

transmission_counts = data['am'].value_counts()
plt.figure(figsize=(8, 6))
transmission_counts.plot(kind='bar', color='red')
plt.title('Frequency Distribution of Transmission Type')
plt.xlabel('Transmission Type (0 = Automatic, 1 = Manual)')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(10, 20))
plt.boxplot(data['mpg'], vert=False, notch=False, patch_artist=True, boxprops=dict(facecolor='green'))
plt.boxplot(data['mpg'], vert=False, notch=True, patch_artist=True, boxprops=dict(facecolor='black'))
plt.title('Box & Whisker Plot of MPG')
plt.xlabel('MPG')
plt.show()