# -*- coding: utf-8 -*-
"""CIE-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kFP2bFFR1Dg3tjlt8C8SqUbdu9G9bfk0

**Conditional Probability**
"""

PA=0.4
PB=0.3
PAB=0.2
print(PAB/PB)

"""**Joint Probability**"""

sample_data={1,2,3,4,5,6}
PA=1/6
PB=1/6
print(PA*PB)

"""**Deal with missing Values**"""

import pandas as pd
df = pd.read_csv('/content/titanic.csv')
df

df.info()

df.duplicated().sum()

df['Sex'].unique()

df.isnull().sum()

import numpy as np
df.replace(np.nan,'0',inplace = True)
df.isnull().sum()

"""**Central Tendency for Age and Fare**"""

import pandas as pd
import seaborn as sns
data = pd.read_csv('/content/titanic.csv')
age_mean = data['Age'].mean()
age_median = data['Age'].median()
age_mode = data['Age'].mode().values[0]

fare_mean = data['Fare'].mean()
fare_median = data['Fare'].median()
fare_mode = data['Fare'].mode().values[0]

print("Central Tendency for Age:")
print(f"Mean: {age_mean:.2f}")
print(f"Median: {age_median}")
print(f"Mode: {age_mode}")

print("\nCentral Tendency for Fare:")
print(f"Mean: {fare_mean:.2f}")
print(f"Median: {fare_median}")
print(f"Mode: {fare_mode}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
titanic_data = pd.read_csv('/content/titanic.csv')
titanic_data['Survived'] = titanic_data['Survived'].replace({0: 'Not Survived', 1: 'Survived'})
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")
sns.countplot(x="Survived", hue="Pclass", data=titanic_data, palette="Set2")
plt.title("Survival Count by Pclass")
plt.xlabel("Survived")
plt.ylabel("Count")
plt.show()

import pandas as pd
df = pd.read_csv('/content/titanic (2).csv')
df.fillna(df.mean(numeric_only=True), inplace=True)
df.fillna('Unknown', inplace=True)
missing_values = df.isnull().sum()
print("After filling missing values:")
print(missing_values)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('titanic.csv')

from scipy import stats
z_scores = np.abs(stats.zscore(df['Fare']))
threshold = 4
outliers = df['Fare'][z_scores > threshold]
plt.figure(figsize=(40, 15))
sns.boxplot(x='Fare', data=df, color='skyblue')
plt.title('Box Plot of Fare Column (with Outliers)')
plt.xlabel('Fare')
plt.show()
print("Outlier values for 'Fare' column:")
print(outliers)